File has BOM, which is causing errors
BOM = Byte Order Mark
Error encountered:
/usr/lib/ruby/gems/1.8/gems/devise_ldap_authenticatable-0.7.0/lib/devise_ldap_authenticatable/model.rb:1: undefined method `﻿require' for main:Object (NoMethodError)